//
//  PreviewInteractor.swift
//  Angie
//
//  Created by Suhendra Ahmad on 7/5/17.
//  Copyright (c) 2017 Suhendra Ahmad. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PreviewBusinessLogic
{
    func loadPhoto(request: Preview.Photo.Request)
}

protocol PreviewDataStore
{
    var photo: FlickrPhoto { get set }
}

class PreviewInteractor: PreviewBusinessLogic, PreviewDataStore
{
    var presenter: PreviewPresentationLogic?
    var worker = PreviewWorker()
    var photo = FlickrPhoto()
    
    // MARK: Do something
    
    func loadPhoto(request: Preview.Photo.Request)
    {
        let response = Preview.Photo.Response(photo: photo)
        presenter?.presentPhoto(response: response)
    }
}
