//
//  GalleryPresenter.swift
//  Angie
//
//  Created by Suhendra Ahmad on 7/4/17.
//  Copyright (c) 2017 Suhendra Ahmad. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GalleryPresentationLogic
{
    func presentPhotos(response: Gallery.Photo.Response)
}

class GalleryPresenter: GalleryPresentationLogic
{
    weak var viewController: GalleryDisplayLogic?
    
    // MARK: Do something
    
    func presentPhotos(response: Gallery.Photo.Response)
    {
        let viewModel = Gallery.Photo.ViewModel(success: response.success, photos: response.photos)
        viewController?.displayPhotos(viewModel: viewModel)
    }
}
