//
//  GalleryInteractor.swift
//  Angie
//
//  Created by Suhendra Ahmad on 7/4/17.
//  Copyright (c) 2017 Suhendra Ahmad. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GalleryBusinessLogic
{
    func fetchPhotos(request: Gallery.Photo.Request)
}

protocol GalleryDataStore
{
    var photos: [FlickrPhoto] { get }
}

class GalleryInteractor: GalleryBusinessLogic, GalleryDataStore
{
    var presenter: GalleryPresentationLogic?
    var worker = GalleryWorker()
    
    var photos: [FlickrPhoto] = []
    
    // MARK: Do something
    
    func fetchPhotos(request: Gallery.Photo.Request)
    {
        worker.fetchPhotos(completionHandler: { (success, photos) in
            
            self.photos = photos
            
            let response = Gallery.Photo.Response(success: success, photos: photos)
            self.presenter?.presentPhotos(response: response)
            
        })
        
        
    }
}
